version: '2.4'

services:
  links-shortener:
    image: disterru/links-shortener
    container_name: links-shortener
    depends_on:
      redis:
        condition: service_started
    environment:
      SERVER_PORT: 80
    ports:
      - "80:80"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
